### ISSUE TITLE
rc_driver.py error 

### ISSUE THREAD

**Issue by Moha-alfridi** [hamuchiwa/AutoRCCar#105]
Hi @hamuchiwa ..
So I am at the final stages of making your project, so after running the `rc_driver.py` I got this error ,

```
Traceback (most recent call last):
  File "/Users/moha/Desktop/AutoRCCar/computer/rc_driver.py", line 145, in <module>
    class VideoStreamHandler(SocketServer.StreamRequestHandler):
  File "/Users/moha/Desktop/AutoRCCar/computer/rc_driver.py", line 153, in VideoStreamHandler
    model = NeuralNetwork()
  File "/Users/moha/Desktop/AutoRCCar/computer/rc_driver.py", line 17, in __init__
    self.model = cv2.ml.ANN_MLP()
AttributeError: 'module' object has no attribute 'ANN_MLP'
```

I am running it on opencv3 and python 2.7

**Comment by hamuchiwa** [comment]
Please refer to [here](https://github.com/hamuchiwa/AutoRCCar/issues/60). You need to reflect the changes relate to OpenCV3.
