### ISSUE TITLE
CV2.cv2 Has no attribute AMN_ML

### ISSUE THREAD

**Issue by JaccoVeldscholten** [hamuchiwa/AutoRCCar#116]
I'm getting an error while running the RC_Driver.py code. It might be an update of OpenCV that causes this. 
**The Error**
`Traceback (most recent call last):
  File "C:/Users/Jacco/PycharmProjects/VironCar/computer/rc_driver.py", line 143, in <module>
    class VideoStreamHandler(socketserver.StreamRequestHandler):
  File "C:/Users/Jacco/PycharmProjects/VironCar/computer/rc_driver.py", line 151, in VideoStreamHandler
    model = NeuralNetwork()
  File "C:/Users/Jacco/PycharmProjects/VironCar/computer/rc_driver.py", line 15, in __init__
    self.model = cv2.ANN_MLP()
AttributeError: module 'cv2.cv2' has no attribute 'ANN_MLP'`

**Piece of code**
`    def __init__(self):
        self.model = cv2.ANN_MLP()`

**PC Info**
- Linux Debian Python 3
- Windows Python 3 (Python 2 same issue)
- Open CV 3.4.1.15
Switching to V2 didn't work

**Comment by hamuchiwa** [comment]
Yes, you are correct, it's because of OpenCV3. Take a look at #60.
