### ISSUE TITLE
rc_driver.py gives traceback in create self.model.create(layer_size)

### ISSUE THREAD

**Issue by aakashm301** [hamuchiwa/AutoRCCar#83]
**THE ERRORS**

C:\ProgramData\Anaconda3\python.exe "C:/Users/Aakash/Desktop/AutoRCCar-master/computer/rc_driver 3.py"
Traceback (most recent call last):
  File "C:/Users/Aakash/Desktop/AutoRCCar-master/computer/rc_driver 3.py", line 145, in <module>
    class VideoStreamHandler(socketserver.StreamRequestHandler):
  File "C:/Users/Aakash/Desktop/AutoRCCar-master/computer/rc_driver 3.py", line 154, in VideoStreamHandler
    model.create()
  File "C:/Users/Aakash/Desktop/AutoRCCar-master/computer/rc_driver 3.py", line 21, in create
    self.model.create(layer_size)
SystemError: <built-in method create of type object at 0x00007FFA6199C170> returned NULL without setting an error

Process finished with exit code 1

> I am using opencv 3.4
> and python 3.6

**Comment by hamuchiwa** [comment]
You need to reflect all the changes from OpenCV2 to OpenCV3. I'll keep this [thread](https://github.com/hamuchiwa/AutoRCCar/issues/60#issuecomment-356751492) open instead.
